#!/usr/bin/env bash
set -e
pushd ~/.config/nixos/
nvim configuration.nix
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch &>nixos-switch.log || (
	cat nixos-switch.log | grep --color error && false )
cat nixos-switch.log | grep --color error || true
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
popd
